dist: bionic
language: csharp
mono: none
services:
  - postgresql
before_script:
  - psql -c "alter user postgres password '1234'" -U postgres
sudo: required
dotnet: 3.1
solution: DynamicQueryBuilder.sln
script:
- scripts/test.sh
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./scripts/deploy.sh && ./scripts/deploy.sh $NUGET_API_KEY $NUGET_SOURCE
  on:
    branch: master